name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev libevdev-dev
      - uses: treeform/setup-nim-action@v6
      - run: nimby sync nimby.lock -g
      - run: nim check src/planet_wars.nim
      - run: nim r tests/tests.nim
